import express from 'express';

const clampText=(v,n=4000)=>String(v??'').trim().slice(0,n);
const safetyClass=(text)=>{const t=text.toLowerCase();return /(خودکشی|خودم را بکشم|self[- ]?harm|suicide|kill myself)/i.test(t)?'urgent_review':/(غمگین|اضطراب|استرس|sad|anxious|stress)/i.test(t)?'supportive':'ordinary'};
const localGuide=(kind,text,klass)=>{if(klass==='urgent_review')return 'من نمی‌توانم جای کمک فوری یا متخصص را بگیرم. اگر خطر فوری وجود دارد، همین حالا با یک فرد قابل اعتماد در نزدیکی خود یا خدمات اضطراری محلی تماس بگیر. می‌توانیم فقط روی قدم امن بعدی تمرکز کنیم.';if(kind==='study')return `پیشنهاد مطالعه: هدف را به یک بخش ۲۵ دقیقه‌ای کوچک تبدیل کن، بعد ۵ دقیقه استراحت و در پایان سه نکته را بدون نگاه‌کردن مرور کن. موضوع فعلی: ${text.slice(0,180)}`;if(kind==='planner')return 'پیشنهاد برنامه‌ریزی: فقط سه اولویت امروز را انتخاب کن؛ کار سخت‌تر را به کوچک‌ترین اقدام قابل شروع بشکن و زمان واقع‌بینانه برای استراحت نگه دار.';return 'می‌توانم برای خودبازتابی و عادت‌های حمایتی کمک کنم، نه تشخیص پزشکی. احساس را نام‌گذاری کن، شدت آن را بسنج و یک اقدام کوچک مثل آب، استراحت، حرکت کوتاه یا صحبت با فرد قابل اعتماد انتخاب کن.'};

export function createPhase4Router({pool,auth}){
 const r=express.Router(); r.use(auth);
 r.post('/learning/goals',async(req,res)=>{const title=clampText(req.body.title,240);if(!title)return res.status(400).json({error:'invalid_input'});const q=await pool.query('insert into learning_goal(owner_user_id,subject_id,title,target) values($1,$2,$3,$4) returning *',[req.identity.sub,req.body.subjectId||null,title,clampText(req.body.target,1000)||null]);res.status(201).json(q.rows[0])});
 r.get('/learning/goals',async(req,res)=>{const q=await pool.query("select * from learning_goal where owner_user_id=$1 and status<>'archived' order by created_at desc",[req.identity.sub]);res.json({items:q.rows})});
 r.post('/learning/checkins',async(req,res)=>{const c=Number(req.body.confidence),d=Number(req.body.difficulty);if(!Number.isInteger(c)||c<1||c>5||!Number.isInteger(d)||d<1||d>5)return res.status(400).json({error:'invalid_input'});const q=await pool.query('insert into learning_checkin(owner_user_id,learning_goal_id,confidence,difficulty,note) values($1,$2,$3,$4,$5) returning *',[req.identity.sub,req.body.learningGoalId||null,c,d,clampText(req.body.note,2000)||null]);res.status(201).json(q.rows[0])});
 r.post('/wellbeing/checkins',async(req,res)=>{const m=Number(req.body.mood),e=Number(req.body.energy),s=Number(req.body.stress);if(![m,e,s].every(x=>Number.isInteger(x)&&x>=1&&x<=5))return res.status(400).json({error:'invalid_input'});const visibility=req.body.visibility==='guardian_summary'?'guardian_summary':'private';const q=await pool.query('insert into wellbeing_checkin(owner_user_id,mood,energy,stress,note,visibility) values($1,$2,$3,$4,$5,$6) returning id,mood,energy,stress,visibility,created_at',[req.identity.sub,m,e,s,clampText(req.body.note,2000)||null,visibility]);res.status(201).json(q.rows[0])});
 r.get('/wellbeing/checkins',async(req,res)=>{const q=await pool.query('select id,mood,energy,stress,visibility,created_at from wellbeing_checkin where owner_user_id=$1 order by created_at desc limit 30',[req.identity.sub]);res.json({items:q.rows})});
 r.post('/ai/sessions',async(req,res)=>{const kind=['study','planner','wellbeing'].includes(req.body.kind)?req.body.kind:null;if(!kind)return res.status(400).json({error:'invalid_kind'});const q=await pool.query('insert into ai_guide_session(owner_user_id,guide_kind) values($1,$2) returning *',[req.identity.sub,kind]);res.status(201).json(q.rows[0])});
 r.post('/ai/sessions/:id/messages',async(req,res)=>{const text=clampText(req.body.message);if(!text)return res.status(400).json({error:'invalid_input'});const s=await pool.query("select * from ai_guide_session where id=$1 and owner_user_id=$2 and status='active'",[req.params.id,req.identity.sub]);if(!s.rowCount)return res.status(404).json({error:'session_not_found'});const klass=safetyClass(text);await pool.query("insert into ai_guide_message(session_id,author,body,safety_class) values($1,'user',$2,$3)",[req.params.id,text,klass]);const reply=localGuide(s.rows[0].guide_kind,text,klass);const q=await pool.query("insert into ai_guide_message(session_id,author,body,safety_class) values($1,'assistant',$2,$3) returning id,body,safety_class,created_at",[req.params.id,reply,klass]);res.json({...q.rows[0],advisory:true,medicalDiagnosis:false,automaticAction:false})});
 r.post('/ai/proposals',async(req,res)=>{const title=clampText(req.body.title,240);if(!title||!req.body.proposal||typeof req.body.proposal!=='object')return res.status(400).json({error:'invalid_input'});const q=await pool.query('insert into ai_plan_proposal(owner_user_id,session_id,title,proposal) values($1,$2,$3,$4) returning *',[req.identity.sub,req.body.sessionId||null,title,req.body.proposal]);res.status(201).json(q.rows[0])});
 r.patch('/ai/proposals/:id',async(req,res)=>{const status=['accepted','rejected'].includes(req.body.status)?req.body.status:null;if(!status)return res.status(400).json({error:'invalid_status'});const q=await pool.query("update ai_plan_proposal set status=$3,decided_at=now() where id=$1 and owner_user_id=$2 and status='proposed' returning *",[req.params.id,req.identity.sub,status]);if(!q.rowCount)return res.status(404).json({error:'proposal_not_found'});res.json(q.rows[0])});
 return r;
}
