import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'api.dart';

class IranHubApi {
  IranHubApi(this.identity,{String? baseUrl}):baseUrl=baseUrl??const String.fromEnvironment('LIFEMATE_API_URL',defaultValue:'http://localhost:8080');
  final IdentityApi identity; final String baseUrl;
  Future<Map<String,dynamic>> call(String method,String path,{Map<String,dynamic>? body}) async {
    final req=http.Request(method,Uri.parse('$baseUrl$path'))..headers.addAll({'content-type':'application/json','authorization':'Bearer ${identity.accessToken??''}'});
    if(body!=null)req.body=jsonEncode(body); final res=await http.Response.fromStream(await req.send());
    if(res.statusCode<200||res.statusCode>=300)throw Exception('request_failed_${res.statusCode}');
    return res.body.isEmpty?<String,dynamic>{}:jsonDecode(res.body) as Map<String,dynamic>;
  }
}

String iranStageLabel(int grade){if(grade<=3)return 'دوره اول ابتدایی';if(grade<=6)return 'دوره دوم ابتدایی';if(grade<=9)return 'دوره اول متوسطه';return 'دوره دوم متوسطه';}
int iranLocalYear(int grade)=>grade<=3?grade:grade<=6?grade-3:grade<=9?grade-6:grade-9;

class IranianFamilyLearningHub extends StatefulWidget { const IranianFamilyLearningHub({super.key,required this.api}); final IdentityApi api; @override State<IranianFamilyLearningHub> createState()=>_IranianFamilyLearningHubState(); }
class _IranianFamilyLearningHubState extends State<IranianFamilyLearningHub>{
  late IranHubApi api; int tab=0; late Future<List<Map<String,dynamic>>> future;
  @override void initState(){super.initState();api=IranHubApi(widget.api);future=load();}
  Future<List<Map<String,dynamic>>> load() async=>[await api.call('GET','/v1/me/iran-profile'),await api.call('GET','/v1/education/catalog?grade=7&schoolYear=1405-1406'),await api.call('GET','/v1/calendar/iran?year=1405'),await api.call('GET','/v1/me/notification-preferences'),await api.call('GET','/v1/me/menstrual-cycles')];
  Future<void> refresh()async{setState(()=>future=load());await future;}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('مرکز خانواده و یادگیری ایران')),body:FutureBuilder<List<Map<String,dynamic>>>(future:future,builder:(context,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());final d=s.data!;final pages=[ProfileEducationPane(api:api,data:d[0],onSaved:refresh),CurriculumPane(data:d[1]),IranCalendarPane(data:d[2]),NotificationPane(api:api,data:d[3],onSaved:refresh),CyclePane(api:api,data:d[4],onSaved:refresh)];return pages[tab];}),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(v)=>setState(()=>tab=v),destinations:const [NavigationDestination(icon:Icon(Icons.family_restroom),label:'نقش'),NavigationDestination(icon:Icon(Icons.school),label:'درس‌ها'),NavigationDestination(icon:Icon(Icons.calendar_month),label:'تقویم'),NavigationDestination(icon:Icon(Icons.notifications),label:'یادآوری'),NavigationDestination(icon:Icon(Icons.favorite_outline),label:'خصوصی')]));
}

class ProfileEducationPane extends StatefulWidget{const ProfileEducationPane({super.key,required this.api,required this.data,required this.onSaved});final IranHubApi api;final Map<String,dynamic> data;final Future<void> Function() onSaved;@override State<ProfileEducationPane> createState()=>_ProfileEducationPaneState();}
class _ProfileEducationPaneState extends State<ProfileEducationPane>{late String persona;late String sex;late int grade;@override void initState(){super.initState();persona=widget.data['household_persona']?.toString()??'child';sex=widget.data['sex']?.toString()??'unspecified';grade=int.tryParse(widget.data['national_grade']?.toString()??'7')??7;}Future<void> save()async{await widget.api.call('PATCH','/v1/me/iran-profile',body:{'householdPersona':persona,'sex':sex});if(persona=='child')await widget.api.call('PUT','/v1/me/education',body:{'nationalGrade':grade,'schoolYear':'1405-1406'});await widget.onSaved();} @override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:[const Text('نقش خانوادگی',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:12),DropdownButtonFormField(value:persona,items:const [DropdownMenuItem(value:'mother',child:Text('مادر')),DropdownMenuItem(value:'father',child:Text('پدر')),DropdownMenuItem(value:'child',child:Text('فرزند')),DropdownMenuItem(value:'adult',child:Text('بزرگسال'))],onChanged:(v)=>setState(()=>persona=v!),decoration:const InputDecoration(labelText:'نقش')),const SizedBox(height:12),DropdownButtonFormField(value:sex,items:const [DropdownMenuItem(value:'female',child:Text('دختر / زن')),DropdownMenuItem(value:'male',child:Text('پسر / مرد')),DropdownMenuItem(value:'unspecified',child:Text('ذکر نشود'))],onChanged:(v)=>setState(()=>sex=v!),decoration:const InputDecoration(labelText:'جنسیت')),if(persona=='child')...[const SizedBox(height:12),DropdownButtonFormField(value:grade,items:[for(var g=1;g<=12;g++)DropdownMenuItem(value:g,child:Text('پایه $g — ${iranStageLabel(g)}، سال ${iranLocalYear(g)}'))],onChanged:(v)=>setState(()=>grade=v!),decoration:const InputDecoration(labelText:'پایه تحصیلی'))],const SizedBox(height:16),FilledButton(onPressed:save,child:const Text('ذخیره'))]);}

class CurriculumPane extends StatelessWidget{const CurriculumPane({super.key,required this.data});final Map<String,dynamic> data;@override Widget build(BuildContext context){final rows=data['subjects'] as List<dynamic>???const[];return ListView(padding:const EdgeInsets.all(16),children:[const Text('پایه هفتم — دوره اول متوسطه، سال اول',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:6),const Text('کتاب‌ها از منبع رسمی لینک می‌شوند؛ فایل PDF بدون مجوز بازتوزیع داخل برنامه بسته‌بندی نمی‌شود.'),const SizedBox(height:12),...rows.map((r){final m=Map<String,dynamic>.from(r as Map);return Card(child:ListTile(leading:const Icon(Icons.menu_book),title:Text(m['name_fa']?.toString()??''),subtitle:Text('${m['publisher']??''}\n${m['source_url']??''}')));})]);}}
class IranCalendarPane extends StatelessWidget{const IranCalendarPane({super.key,required this.data});final Map<String,dynamic> data;@override Widget build(BuildContext context){final rows=data['events'] as List<dynamic>???const[];return ListView(padding:const EdgeInsets.all(16),children:[const Text('تقویم جلالی ۱۴۰۵',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const Text('شروع هفته: شنبه · آخرهفته پیش‌فرض: پنج‌شنبه و جمعه · تعطیل هفتگی رسمی: جمعه'),const SizedBox(height:12),...rows.map((r){final m=Map<String,dynamic>.from(r as Map);return Card(child:ListTile(leading:Icon(m['is_official_holiday']==true?Icons.event_busy:Icons.event),title:Text(m['title_fa']?.toString()??''),subtitle:Text('${m['jalali_month']}/${m['jalali_day']} · ${m['source_name']??''}')));})]);}}
class NotificationPane extends StatelessWidget{const NotificationPane({super.key,required this.api,required this.data,required this.onSaved});final IranHubApi api;final Map<String,dynamic> data;final Future<void> Function() onSaved;Future<void> set(String key,bool value)async{await api.call('PATCH','/v1/me/notification-preferences',body:{key:value});await onSaved();}@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:[SwitchListTile(title:const Text('بنر داخل برنامه'),value:data['in_app_banner']==true,onChanged:(v)=>set('inAppBanner',v)),SwitchListTile(title:const Text('یادآوری برنامه'),value:data['planner_reminders']!=false,onChanged:(v)=>set('plannerReminders',v)),SwitchListTile(title:const Text('یادآوری مدرسه'),value:data['school_reminders']!=false,onChanged:(v)=>set('schoolReminders',v)),SwitchListTile(title:const Text('یادآوری تقویم'),value:data['calendar_reminders']!=false,onChanged:(v)=>set('calendarReminders',v)),SwitchListTile(title:const Text('نمایش متن حساس روی اعلان'),subtitle:const Text('به‌صورت پیش‌فرض خاموش است.'),value:data['sensitive_preview']==true,onChanged:(v)=>set('sensitivePreview',v))]);}
class CyclePane extends StatelessWidget{const CyclePane({super.key,required this.api,required this.data,required this.onSaved});final IranHubApi api;final Map<String,dynamic> data;final Future<void> Function() onSaved;Future<void> add()async{final now=DateTime.now();await api.call('POST','/v1/me/menstrual-cycles',body:{'startsOn':'${now.year}-${now.month.toString().padLeft(2,'0')}-${now.day.toString().padLeft(2,'0')}','reminderEnabled':false});await onSaved();}@override Widget build(BuildContext context){final rows=data['entries'] as List<dynamic>???const[];return ListView(padding:const EdgeInsets.all(16),children:[const Text('چرخه شخصی',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const Text('کاملاً خصوصی برای صاحب حساب؛ ابزار ثبت و یادآوری است و کاربرد تشخیصی ندارد.'),const SizedBox(height:12),FilledButton.icon(onPressed:add,icon:const Icon(Icons.add),label:const Text('ثبت شروع امروز')),...rows.map((r){final m=Map<String,dynamic>.from(r as Map);return Card(child:ListTile(title:Text('شروع: ${m['starts_on']}'),subtitle:Text(m['notes']?.toString()??'')));})]);}}
